---
title: "Week 5 - Latent Constructs"
---

## Overview

A major criticism of big data and other “naturally occurring” records is that they have lots of information, but do they include the things we need and want to know? Put another way, what are they capable of measuring about people, places, and things? In this module, you will answer this question using two tools. The first is a schema, which allows us to understand how records connect to other data sets based on the very people, places, and things we want to know more about. The second is an approach to measurement that organizes the world into latent constructs, or underlying characteristics that we believe exist, and manifest variables, or measurable elements that reflect latent constructs. Through this lens, we can build measures that describe the features of those people, places, and things. We see this approach illustrated in a chapter about the work that my own organization, the Boston Area Research Initiative, has done to translate administrative data into a series of ecometrics that describe the social and physical characteristics of the neighborhoods of Boston.

### Learning objectives

- Describe the schema associated with a dataset.
- Propose aggregate measures from naturally-occurring data that are rooted in concepts of interest.
- Subset a data frame based on the contents of another data frame.
- Consider the implications of the data-generation process for the interpretation of aggregate variables.


## Substantive Readings 

- [O'Brien _2018_ The Urban Commons Chapter 2](https://northeastern.instructure.com/courses/65223/files/6696416/download?wrap=1): Through pg. 65 and 85-90 required; summary sections for the rest of the chapter will suffice.

### Prompt

- What is the 'ecometric' approach to big data and how does it solve the problem of ‘measurement’ in urban big data?
- How does it fit in with BARI's broader vision?

## Service Learning Response 

Now that you’ve completed your midterm, how did the city walk and in-class workshop influence the practical application of your analysis in working with the data? Going forward, what are your goals in this aspect (practical application-wise)?

## Data Assignment

For this week's data assignment, propose at least one latent construct that you would like to measure with your data set and the geographic level at which you would want to measure it.

In addition, describe how this construct is interesting and at least one manifest variable for measuring it. Use the latent construct modeling notation from this week's lesson presentation to bring it across.

Note: Your manifest variable can be an idea at this point and we can figure out how to code it in R in the coming weeks.
