---
title: "Week 6 - Linking Data"
---


## Overview

Data come from many different sources—in this class alone you all are working with multiple data sets that describe distinct aspects of the city. Part of the opportunity of “big data” is the potential to coordinate these data sets in order to analyze them in conjunction with each other. In order to do so, however, we must leverage the schemas we learned about in the last module—that is, the people, places, and things that they share in common—to link them. In this module, you will leverage the geographical infrastructure of Boston to develop aggregate measures describing some unit of analysis (e.g., streets, census tracts), and then link them with other information describing those same units. We will also learn about the Actionable Intelligence for Social Policy’s efforts to solve this same problem for linking information about individuals across the data generated by the many different agencies responsible for health and human services.

### Learning objectives

- Calculate measures at aggregate levels from records
- Link data from different sources using shared units of analysis in a schema
- Visualize two variables together in a dot plot in ggplot2
- Evaluate the validity of measures
- Evaluate the trade-offs surrounding data analysis and privacy

## Substantive Readings

Choose one of the two papers: 

- [Culhane et al. (2007). "Testing a typology of family homelessness based on patterns of public shelter utilization in four U.S. jurisdictions"](https://northeastern.instructure.com/courses/65223/files/6696418/download?wrap=1)
- [Bowden et al. (2020). "Case identification of mental health and related problems in children and young people using the New Zealand Integrated Data Infrastructure."](https://northeastern.instructure.com/courses/65223/files/6696419/download?wrap=1)

And peruse [Actionable Intelligence for Social Policy](https://www.aisp.upenn.edu/).

### Prompt

IDSes merge a wealth of personal data to support comprehensive scholarly and policy analysis.

Try to draw a diagram of the schema that you think enabled the study that you read. What other research questions do you think that that the data in that schema might be able to answer?

## Technical Readings

- Lander: Chapters 11.2, 12.1
- UITK:
  - [Summary Statistics](https://ui.josiahparry.com/summary-statistics.html)
  - [Summarizing the tidy way](https://ui.josiahparry.com/summarizing-the-tidy-way.html)
  - [Multiple data sets](https://ui.josiahparry.com/multiple-data-sets.html)
- [R4DS - Grouped summarise with summarise()](https://r4ds.had.co.nz/transform.html#grouped-summaries-with-summarise)

## Data Assignment

Last week you identified a latent construct and the manifest variables that will help you create it. For this week's data assignment create your latent construct and conduct an analysis base on it.  

- Be sure to describe why the construct is interesting and how the specific calculations you are using capture it.
- As you analyze the content of these new variables, be sure to include at least one scatter plot that shows the relationships between two variables (one being your latent construct). 

Please submit your rendered output as well as the original Rmd document. 

## Assignment - Service Learning Response 

Now that you've completed your midterm, how did the city walk and in-class workshop influence the practical application of your analysis in working with the data? Going forward, what are your goals in this aspect (practical application-wise)?

Due Friday at 23:59.

2 - 3 pages double spaced. 
