---
title: "Week 1 - Telling a Data Story"
---

## Overview

Most data come to us as a set of rows (or cases) with values for a set of columns (or variables). But their composite is so much more than that. Each row provides us with a detailed description of a case, be it an object or event, and the variables provide an opportunity to compare across these cases. This enables us not only to translate the information contained in any given row into a data story but also a more general understanding of the knowledge contained in the data themselves.

In this module, you will use basic R functions to expose details of a data frame, particularly the content of individual cases, and use that information to describe the contents of a data set.

To complement our introduction to R, we will explore the fundamental themes of urban informatics by discussing an initial set of readings on 311 systems and New York City’s Mayor’s Office of Data Analytics.

## Learning objectives

- Run R scripts in RStudio to interact with data objects
- Use basic R commands to expose and interpret details of a data frame for individual case
- Utilize R’s technical documentation to explore new functions
- Consider the implications of how a data record is generated
- Describe the five fundamental themes of the field of Urban Informatics

## Substantive Readings

- [Is the Cost of 311 Systems Worth the Price of - Knowing?](http://www.governing.com/topics/urban/gov-311-systems-cost.html)
- [What a Hundred Million Calls to 311 Reveal about New - York](http://www.wired.com/2010/11/ff_311_new_york/)
- [How Public Data Can Improve Services and Empower - Communities](https://scholars.org/brief/how-public-data-can-improve-services-and-empower-communit- ies)
- [NYC's Mayor's Office of Data Analytics](http://www1.nyc.gov/site/analytics/index.page)

## Technical Readings

- Lander: Chapters 1, 2, 4, 5.1, 6
- UITK: 
  - [R as a calculator](https://ui.josiahparry.com/r-as-a-calculator.html)
  - [Reading Data](https://ui.josiahparry.com/reading-data.html)
  - [Exploratory Visual Analysis](https://ui.josiahparry.com/exploratory-visual-analysis.html)
  - [General Data Manipulation](https://ui.josiahparry.com/general-data-manipulation.html)

## Data Assignment

For this week's data assignment, briefly describe the structure of either your whole data set or of some meaningful subset (number of rows, columns, names of relevant variables).

Describe at least three cases (rows) from this set/subset using the information contained in the variables you see as relevant.

-   What have you learned from these cases individually, and from the differences between them?
-   How do they illustrate what we can learn from these data more generally?
-   Can you infer things about the cases that are not explicitly in the data?

<!-- **Skills needed**: -->

<!-- - read_csv() -->
<!-- - select() -->
<!-- - filter() -->
<!-- - arrange() -->
<!-- - count() -->
<!-- - janitor::tabyl() -->
<!-- - summary() / skimr::skim() -->



